version: '3.3'

services:
  nsccronograma:
    volumes: 
      - vol-cronograma:/logs 
    deploy:
        resources:
            limits:
              cpus: 2.00
              memory: 1024M
      
volumes:
  vol-cronograma:
    driver_opts: 
      type: "nfs"
      o: "addr=hom-nfs-siscom.sistemas.cesan.com.br,nolock,soft,rw"
      device: ":/nfs/nsc/cronograma/logs"
